Feature/3774
RTGS-OpenSource/cbs-simulator pull request #175
Opened 2022-05-20 12:59 UTC by Darren-Osborne

2022-05-20 13:51 UTC, josephreillyltd commented on src/RTGS.Bank.Simulator.StubServer/RTGS.Bank.Simulator.StubServer.csproj
> +    <PackageReference Include="RTGS.DotNetSDK" Version="0.1.35" />
I think this needs bumping further

2022-05-20 13:55 UTC, Darren-Osborne commented on src/RTGS.Bank.Simulator.StubServer/RTGS.Bank.Simulator.StubServer.csproj
> +    <PackageReference Include="RTGS.DotNetSDK" Version="0.1.35" />
indeed - done

2022-05-23 08:46 UTC, Bassetts requested changes

2022-05-23 08:46 UTC, Bassetts commented on src/RTGS.Bank.Simulator.IntegrationTests/testsettings.json
> +	"IdCryptServiceAddress": "http://localhost:5301",
Probably the same comment as for `launchsettings.json` applies here regarding the port

2022-05-23 08:46 UTC, Bassetts commented on src/RTGS.Bank.Simulator.Tests/Services/IdCryptConnectionsProviderTests.cs
> +			IdCryptServiceAddress = new Uri("Http://localhost")
Is this right? The connection provider still uses the IDC SDK so I think `IdCryptApiAddress` is still correct here.

2022-05-23 08:46 UTC, Bassetts commented on src/RTGS.Bank.Simulator/Properties/launchSettings.json
> +				"IdCryptServiceAddress": "https://localhost:7033", // "http://idcrypt-cloud-agent-service.com",
This is my bad, I think the service runs on 5107 for http locally.

2022-05-23 09:18 UTC, Darren-Osborne commented on src/RTGS.Bank.Simulator.Tests/Services/IdCryptConnectionsProviderTests.cs
> +			IdCryptServiceAddress = new Uri("Http://localhost")
Actually - as far as this test class is concerned neither are required - have removed now.

2022-05-23 09:28 UTC, Darren-Osborne commented on src/RTGS.Bank.Simulator.IntegrationTests/testsettings.json
> +	"IdCryptServiceAddress": "http://localhost:5301",
Because we use StatusCodeHttpHandler the url/port is irrelevent in the settings (except the RemoteHost one - because that uses the Kestrel server) - have updated the settings to http://urlisignoredforintegration.tests to make this clearer

2022-05-23 09:32 UTC, Bassetts approved these changes

2022-05-23 09:40 UTC, merged